name: 'Mirror repo to public'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Mirror
        run: |
          git config --global user.name Digitraffic
          git config --global user.email digitraffic@fintraffic.fi
          rm -rf .git .github
          git init
          git add .
          git commit -m "Digitraffic rail history"
          git push --mirror git@github.com:mprencipe/digitraffic-rail-history-test
