name: 'Mirror repo to public'

env:
  secret: ${{ secrets.SSH_PRIVATE_KEY }}

on: [push]
jobs:
  mirror:
        if: ${{ env.secret != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Mirror
        run: |
          git push --mirror git@github.com:mprencipe/digitraffic-rail-history-test
