name: 'Mirror repo to public'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install git-filter-repo
        run: |
          pip3 install git-filter-repo
      - name: Mirror
        run: |
          git filter-repo --path .github --invert-paths --force
          git push --mirror git@github.com:mprencipe/digitraffic-rail-history-test
